GET http://localhost:8080/locations
Accept: application/json

###
GET http://localhost:8080/locations?prefix=Nowhere
Accept: application/json

###
GET http://localhost:8080/locations?minLat=13.0&maxLon=0.0
Accept: application/json

###
GET http://localhost:8080/locations?minLat=13.0&maxLat=50.0
Accept: application/json

###
GET http://localhost:8080/locations/5
Accept: application/json

###
PUT http://localhost:8080/locations/2
Content-Type: application/json
Accept: application/json

{
  "name": "HelloThere",
  "lat": -27.6,
  "lon": -18.24
}

###
DELETE http://localhost:8080/locations/2
Accept: application/json

###
POST http://localhost:8080/locations
Content-Type: application/json
Accept: application/json

{
  "name": "HiThere",
  "lat": 27.6,
  "lon": -18.24
}

###
