GET http://localhost:8080/locations
Accept: application/json

###
GET http://localhost:8080/locations?prefix=Nowhere
Accept: application/json

###
GET http://localhost:8080/locations?minLat=13.0&maxLon=0.0
Accept: application/json

###
GET http://localhost:8080/locations?minLat=13.0&maxLat=50.0
Accept: application/json

###
GET http://localhost:8080/locations/2
Accept: application/json

###

